"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""

class Solution:

    def evenFibSum(self, k):
        fib, i = [], 2
        fib.append(1)
        fib.append(2)
        sum = 0
        while fib[i-1] < k:
            fib.append(fib[i-1] + fib[i-2])
            i+=1
        for i in range(len(fib)):
            if fib[i]%2 == 0:
                sum += fib[i]
        return sum
s = Solution()
print(s.evenFibSum(4000000))
